services:
  api:
    container_name: smash_league_api
    ports:
      - 5000:5000
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    # command: bash -c "npx prisma migrate resolve --applied 20250201055158_init_db && echo 'Migration resolved' && node dist/main.js"
    # command: bash -c "npx prisma migrate resolve --applied 20250201055158_init_db && node dist/main.js"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    networks:
      - smashleague
  db:
    image: postgres:17.2
    restart: always
    ports: 
      - "5001:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smashleague
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smashleague

networks:
  smashleague: 
volumes:
  postgres_data: 
