services:
  api:
    container_name: smash_league_api
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://root:password@database.smashit.com.vn:5432/smashleague?schema=public
      - PREFIX=api/v1
      - ACCESS_TOKEN_SECRET_KEY="167031@SmashLeague@ACCESS"
      - REFRESH_TOKEN_SECRET_KEY="167031@SmashLeague@REFRESH"
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=1800
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=25200
    build: 
      context: .
      dockerfile: Dockerfile
    command: bash -c "npx prisma migrate deploy; npx prisma generate; npm run build; npm run start:prod"
    # command: bash -c "npx prisma migrate resolve --applied 20250201055158_init_db && node dist/main.js"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    networks:
      - smashleague
  db:
    container_name: database
    image: postgres:17.2
    restart: always
    ports: 
      - "5002:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smashleague
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smashleague

networks:
  smashleague: {}
volumes:
  postgres_data: 
