services:
  api:
    container_name: smash_league_api
    ports:
      - 5000:5000
    env_file:
      - .env
    build: 
      context: .
      dockerfile: Dockerfile
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npx prisma db seed && npm run build && npm run start:prod"
    # command: bash -c "npx prisma migrate resolve --applied 20250201055158_init_db && node dist/main.js"
    volumes:
      - backend_service:/usr/src/app
    depends_on:
      - db
      - redis
    networks:
      - smashleague
  db:
    container_name: database
    image: postgres:17.2
    restart: always
    ports: 
      - "5002:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: smashleague
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - smashleague
  redis:
    container_name: redis
    image: redis:7.4
    restart: always
    ports: 
      - "6379:6379"
    command: redis-server --save 20 1 --logLevel warning
    volumes:
      - redis_cache:/data
    networks:
      - smashleague
networks:
  smashleague: {}
volumes:
  postgres_data: 
  backend_service:
  redis_cache:
    driver: local
