export enum TournamentTimeJobType {
	CHECK_ENOUGH_PLAYER = "CHECK_ENOUGH_PLAYER",
	DRAW_DATE = "DRAW_DATE",
	START_TOURNAMENT = "START_TOURNAMENT",
	END_TOURNAMENT = "END_TOURNAMENT",
	CLOSE_REGISTRATION = "CLOSE_REGISTRATION",
	OPEN_REGISTRATION = "OPEN_REGISTRATION",
}
