name: backend-service-deployment

on: 
  push:
    branches: 
      main
      
jobs:
  docker-compose: 
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Set up environment variable for docker
      run: |
          touch .env
          echo "${{ secrets.ENV_VARIABLE }}" >> .env
    - name: Display .env file
      run: |
          readlink -f .env
          cat .env
    - name: Run "database"
      run: docker compose up -d db 
    - name: Run "docker compose"
      run: docker compose up --build -d api
