name: backend-service-deployment

on: 
  push:
    branches: 
      main
      
jobs:
  docker-compose: 
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Execute "drop docker volume" before building
      run: |
        docker stop database
        docker rm database
        docker volume rm smash-league-backend_postgres_data
    - name: Run "database"
      run: docker compose up -d db 
    - name: Run "docker compose"
      run: docker compose up --build -d api
