name: backend-service-deployment

on: 
  push:
    branches: 
      main
      
jobs:
  docker-compose: 
    runs-on: self-hosted
    environment: docker
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    # - name: Stop volume and remove exist container before create container
    #   run: |
    #       docker container stop smash_league_api
    #       docker container rm smash_league_api
    #       docker volume rm smash-league-backend_backend_service
    #       docker container stop database
    #       docker container rm database
    #       docker volume rm smash-league-backend_postgres_data
    - name: Set up environment variable for docker
      run: |
          touch .env
          echo "${{ secrets.ENV_VARIABLE }}" >> .env
    - name: Display .env file
      run: |
          readlink -f .env

    - name: Run "database"
      run: docker compose up -d db 
    - name: Run "docker compose"
      run: docker compose up --build -d api
